server:
  port : 8081
spring:
  application:
    name: hinkali-client
  rabbitmq:
    host: localhost
    port: 5672
    username: rmhinkali
    password: rmhinalipassword
    template:
      receive-timeout: 30000